// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6n4eADbH0gdvLrznOOO-T91UlDMN7xx0',
    appId: '1:24052614590:web:30a4127883d8e948e625ef',
    messagingSenderId: '24052614590',
    projectId: 'devhack-3af24',
    authDomain: 'devhack-3af24.firebaseapp.com',
    storageBucket: 'devhack-3af24.appspot.com',
    measurementId: 'G-SLWFCL0SKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJVldampZEJZbOeoi3MBE4Mit752q6-Hs',
    appId: '1:24052614590:android:8bdcdca39a710f3ce625ef',
    messagingSenderId: '24052614590',
    projectId: 'devhack-3af24',
    storageBucket: 'devhack-3af24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6gOGQhmV2gdVMKp2n4KN6vPk6xn-dgSQ',
    appId: '1:24052614590:ios:c9ded10d8fc94263e625ef',
    messagingSenderId: '24052614590',
    projectId: 'devhack-3af24',
    storageBucket: 'devhack-3af24.appspot.com',
    iosClientId: '24052614590-ctc8jeiaqo5892jkr1vgb9fp64s2lv8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.devHack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6gOGQhmV2gdVMKp2n4KN6vPk6xn-dgSQ',
    appId: '1:24052614590:ios:c9ded10d8fc94263e625ef',
    messagingSenderId: '24052614590',
    projectId: 'devhack-3af24',
    storageBucket: 'devhack-3af24.appspot.com',
    iosClientId: '24052614590-ctc8jeiaqo5892jkr1vgb9fp64s2lv8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.devHack',
  );
}
